package org.galaxyworld.flycode.model;

import lombok.Getter;
import lombok.Setter;

public class DatabaseTableColumn {

//    @Setter @Getter
//    private Type type;

    @Getter
    private String sqlName;

    @Setter @Getter
    private String name;

    @Setter @Getter
    private String defaultValue;

    @Setter @Getter
    private String comment;

    @Setter @Getter
    private boolean primaryKey;

    @Setter @Getter
    private boolean autoGenerated;

    @Setter @Getter
    private int size;

    @Setter @Getter
    private boolean notNull;

    @Setter
    private String description;

}
