package org.galaxyworld.flycode.util;

import com.intellij.database.model.DasColumn;
import com.intellij.database.model.DasTable;
import com.intellij.database.psi.DbDataSource;
import com.intellij.database.psi.DbPsiFacade;
import com.intellij.openapi.project.Project;
import org.jetbrains.annotations.Nullable;

import java.util.List;

public class DatabaseUtils {

    public static List<DbDataSource> getDataSources(Project project) {
        return DbPsiFacade.getInstance(project).getDataSources();
    }

    public static boolean isAutoGenerated(@Nullable DasColumn column) {
        return hasAttribute(column, DasColumn.Attribute.AUTO_GENERATED);
    }

    public static boolean hasAttribute(@Nullable DasColumn column, DasColumn.Attribute attribute) {
        DasTable table = column == null ? null : column.getTable();
        return table != null && table.getColumnAttrs(column).contains(attribute);
    }

}
